import { FormEvent,useMemo,useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { Building2,Plus,Trash2 } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Customer,CustomerContact } from '../lib/types'

export function ClientsPage(){
 const qc=useQueryClient();const [selected,setSelected]=useState<Customer|null>(null);const [search,setSearch]=useState('');const [typeFilter,setTypeFilter]=useState('');const [statusFilter,setStatusFilter]=useState('')
 const {data:clients=[]}=useQuery({queryKey:['customers'],queryFn:async()=>{const {data,error}=await supabase.from('customers').select('*').order('name');if(error)throw error;return data as Customer[]}})
 const {data:contacts=[]}=useQuery({queryKey:['contacts',selected?.id],enabled:!!selected,queryFn:async()=>{const {data,error}=await supabase.from('customer_contacts').select('*').eq('customer_id',selected!.id).order('last_name');if(error)throw error;return data as CustomerContact[]}})
 const rows=useMemo(()=>clients.filter(c=>{const q=search.trim().toLowerCase();const txt=(c.name+' '+(c.code||'')+' '+(c.email||'')+' '+(c.phone||'')+' '+(c.city||'')).toLowerCase();if(q&&!txt.includes(q))return false;if(typeFilter&&c.type!==typeFilter)return false;if(statusFilter==='active'&&!c.active)return false;if(statusFilter==='inactive'&&c.active)return false;return true}),[clients,search,typeFilter,statusFilter])
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const row={name:String(fd.get('name')),code:String(fd.get('code')||'')||null,type:String(fd.get('type')||'company'),email:String(fd.get('email')||'')||null,phone:String(fd.get('phone')||'')||null,address:String(fd.get('address')||'')||null,city:String(fd.get('city')||'')||null,postal_code:String(fd.get('postal_code')||'')||null,country:String(fd.get('country')||'France'),notes:String(fd.get('notes')||'')||null,active:true};const q=selected?supabase.from('customers').update(row).eq('id',selected.id):supabase.from('customers').insert(row);const {error}=await q;if(error){alert(error.message);return}setSelected(null);e.currentTarget.reset();await qc.invalidateQueries({queryKey:['customers']})}
 const addContact=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const fd=new FormData(e.currentTarget);const {error}=await supabase.from('customer_contacts').insert({customer_id:selected.id,first_name:String(fd.get('first_name')),last_name:String(fd.get('last_name')),email:String(fd.get('email')||'')||null,phone:String(fd.get('phone')||'')||null,job_title:String(fd.get('job_title')||'')||null});if(error)alert(error.message);else{e.currentTarget.reset();await qc.invalidateQueries({queryKey:['contacts',selected.id]})}}
 const remove=async(c:Customer)=>{if(!confirm('Supprimer le client '+c.name+' ?'))return;const {error}=await supabase.from('customers').delete().eq('id',c.id);if(error)alert(error.message);else{if(selected?.id===c.id)setSelected(null);await qc.invalidateQueries({queryKey:['customers']})}}
 return <div className="page clients-page"><header className="page-head"><div><h1>Base Clients</h1><p>Sociétés, particuliers et contacts liés aux tickets.</p></div><button className="primary page-primary-action" onClick={()=>setSelected(null)}><Plus size={16}/> Nouveau client</button></header>
 <section className="card module-filter-card"><div className="module-filter-title"><b>Recherche & filtres</b><span>{rows.length} résultat{rows.length>1?'s':''}</span></div><div className="module-filter-grid"><label className="wide-filter">Recherche<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom, code, ville, email…"/></label><label>Type<select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">Tous</option><option value="company">Entreprises</option><option value="person">Particuliers</option></select></label><label>Statut<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Tous</option><option value="active">Actifs</option><option value="inactive">Inactifs</option></select></label></div></section>
 <div className="split"><div><div className="table-wrap desktop-only"><table><thead><tr><th>Client</th><th>Contact</th><th>Ville</th><th>Statut</th><th></th></tr></thead><tbody>{rows.map(c=><tr key={c.id} onClick={()=>setSelected(c)} style={{cursor:'pointer'}}><td><b>{c.name}</b><br/><small>{c.code||c.type}</small></td><td>{c.email||'—'}<br/><small>{c.phone||''}</small></td><td>{[c.postal_code,c.city].filter(Boolean).join(' ')||'—'}</td><td><span className={'badge '+(c.active?'green':'red')}>{c.active?'Actif':'Inactif'}</span></td><td><button className="danger small" onClick={e=>{e.stopPropagation();void remove(c)}}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>
 <div className="module-mobile-list">{rows.map(c=><article className="module-mobile-card" key={c.id} onClick={()=>setSelected(c)}><div className="module-mobile-head"><div><b>{c.name}</b><small>{c.code||c.type}</small></div><span className={'badge '+(c.active?'green':'red')}>{c.active?'Actif':'Inactif'}</span></div><div className="module-mobile-meta"><div><span>Email</span><b>{c.email||'—'}</b></div><div><span>Téléphone</span><b>{c.phone||'—'}</b></div><div><span>Ville</span><b>{[c.postal_code,c.city].filter(Boolean).join(' ')||'—'}</b></div><div><span>Pays</span><b>{c.country||'—'}</b></div></div><div className="module-mobile-actions"><button className="danger small" onClick={e=>{e.stopPropagation();void remove(c)}}><Trash2 size={14}/> Supprimer</button></div></article>)}</div></div>
 <aside className="panel detail-panel"><h2>{selected?'Modifier le client':'Nouveau client'}</h2><form className="form-grid" onSubmit={save} key={selected?.id||'new'}><label className="full">Nom<input name="name" defaultValue={selected?.name||''} required/></label><label>Code<input name="code" defaultValue={selected?.code||''}/></label><label>Type<select name="type" defaultValue={selected?.type||'company'}><option value="company">Entreprise</option><option value="person">Particulier</option></select></label><label>Email<input name="email" type="email" defaultValue={selected?.email||''}/></label><label>Téléphone<input name="phone" defaultValue={selected?.phone||''}/></label><label className="full">Adresse<input name="address" defaultValue={selected?.address||''}/></label><label>Code postal<input name="postal_code" defaultValue={selected?.postal_code||''}/></label><label>Ville<input name="city" defaultValue={selected?.city||''}/></label><label>Pays<input name="country" defaultValue={selected?.country||'France'}/></label><label className="full">Notes<textarea name="notes" defaultValue={selected?.notes||''}/></label><button className="primary full">Enregistrer</button></form>
 {selected&&<><hr/><h3>Contacts</h3><div>{contacts.map(c=><div className="card" key={c.id}><b>{c.first_name} {c.last_name}</b><br/><small>{c.job_title||''} • {c.email||''} • {c.phone||''}</small></div>)}</div><form className="form-grid" onSubmit={addContact}><label>Prénom<input name="first_name" required/></label><label>Nom<input name="last_name" required/></label><label>Email<input name="email" type="email"/></label><label>Téléphone<input name="phone"/></label><label className="full">Fonction<input name="job_title"/></label><button className="secondary full">Ajouter le contact</button></form></>}
 </aside></div></div>
}
