import { FormEvent,useMemo,useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { Boxes,PackagePlus } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../auth/AuthProvider'
import type { InventoryItem } from '../lib/types'
import { inventoryAvailable } from '../lib/types'

export function InventoryPage(){
 const {profile}=useAuth();const manager=profile?.role==='manager';const qc=useQueryClient();const [selected,setSelected]=useState<InventoryItem|null>(null);const [search,setSearch]=useState('')
 const {data:items=[]}=useQuery({queryKey:['inventory'],queryFn:async()=>{const {data,error}=await supabase.from('inventory_items').select('*').order('category').order('model');if(error)throw error;return data as InventoryItem[]}})
 const rows=items.filter(i=>(i.category+' '+(i.manufacturer||'')+' '+i.model+' '+(i.reference||'')).toLowerCase().includes(search.toLowerCase()))
 const value=useMemo(()=>items.reduce((s,i)=>s+Number(i.unit_price||0)*i.quantity_total,0),[items])
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const row={category:String(fd.get('category')),manufacturer:String(fd.get('manufacturer')||'')||null,model:String(fd.get('model')),reference:String(fd.get('reference')||'')||null,description:String(fd.get('description')||'')||null,unit_price:Number(fd.get('unit_price')||0),quantity_total:Number(fd.get('quantity_total')||0),stock_minimum:Number(fd.get('stock_minimum')||0),location:String(fd.get('location')||'')||null,tracked_individually:fd.get('tracked')==='on',active:true};const q=selected?supabase.from('inventory_items').update(row).eq('id',selected.id):supabase.from('inventory_items').insert(row);const {error}=await q;if(error)alert(error.message);else{setSelected(null);e.currentTarget.reset();await qc.invalidateQueries({queryKey:['inventory']})}}
 const move=async(i:InventoryItem,type:string)=>{const raw=prompt(type==='STOCK_IN'?'Quantité à ajouter':'Quantité à retirer');if(!raw)return;const quantity=Number(raw);if(!Number.isFinite(quantity)||quantity<=0)return;const note=prompt('Commentaire / référence du mouvement')||'';const {error}=await supabase.rpc('inventory_move',{p_item_id:i.id,p_type:type,p_quantity:quantity,p_note:note});if(error)alert(error.message);else await qc.invalidateQueries({queryKey:['inventory']})}
 const reserve=async(i:InventoryItem)=>{const ticket=prompt('ID du ticket à réserver');if(!ticket)return;const qty=Number(prompt('Quantité')||0);if(qty<=0)return;const {error}=await supabase.rpc('reserve_inventory',{p_ticket_id:ticket,p_item_id:i.id,p_quantity:qty});if(error)alert(error.message);else await qc.invalidateQueries({queryKey:['inventory']})}
 return <div className="page inventory-page"><header className="page-head"><div><h1>{manager?'Inventaire':'Matériel'}</h1><p>Modèles, prix, quantités, réservations et alertes de stock.</p></div>{manager&&<button className="primary inventory-new-btn" onClick={()=>setSelected(null)}><PackagePlus size={16}/> <span>Nouvelle référence</span></button>}</header>
 <section className="grid four inventory-kpis"><div className="kpi"><b>{items.length}</b><span>Références</span></div><div className="kpi"><b>{items.reduce((s,i)=>s+inventoryAvailable(i),0)}</b><span>Unités disponibles</span></div><div className="kpi danger"><b>{items.filter(i=>inventoryAvailable(i)<=i.stock_minimum).length}</b><span>Stocks faibles</span></div><div className="kpi good"><b>{value.toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</b><span>Valeur stock</span></div></section>
 <div className={manager?'split':'grid'}><div><div className="toolbar card"><label>Recherche<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="HP, EliteBook, dock…"/></label></div><div className="table-wrap inventory-table desktop-only"><table><thead><tr><th>Matériel</th><th>Prix</th><th>Total</th><th>Réservé</th><th>Attribué</th><th>Disponible</th><th>Emplacement</th>{manager&&<th>Actions</th>}</tr></thead><tbody>{rows.map(i=>{const available=inventoryAvailable(i);return <tr key={i.id} onClick={()=>manager&&setSelected(i)} style={{cursor:manager?'pointer':'default'}}><td><div className="inventory-name"><b>{i.manufacturer} {i.model}</b><small>{i.category} • {i.reference||'sans référence'}</small></div></td><td className="money">{Number(i.unit_price).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</td><td>{i.quantity_total}</td><td>{i.quantity_reserved}</td><td>{i.quantity_assigned}</td><td className={available<=0?'stock-out':available<=i.stock_minimum?'stock-low':''}>{available}</td><td>{i.location||'—'}</td>{manager&&<td><div className="actions"><button className="secondary small" onClick={e=>{e.stopPropagation();void move(i,'STOCK_IN')}}>+ Stock</button><button className="ghost small" onClick={e=>{e.stopPropagation();void move(i,'STOCK_OUT')}}>- Stock</button><button className="ghost small" onClick={e=>{e.stopPropagation();void reserve(i)}}>Réserver</button></div></td>}</tr>})}</tbody></table></div>
 <div className="inventory-mobile-list mobile-only">{rows.map(i=>{const available=inventoryAvailable(i);return <article className="inventory-mobile-card" key={i.id} onClick={()=>manager&&setSelected(i)}><div className="inventory-mobile-head"><div><b>{[i.manufacturer,i.model].filter(Boolean).join(' ')}</b><small>{i.category} • {i.reference||'sans référence'}</small></div><strong>{Number(i.unit_price).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</strong></div><div className="inventory-mobile-stats"><div><span>Total</span><b>{i.quantity_total}</b></div><div><span>Réservé</span><b>{i.quantity_reserved}</b></div><div><span>Attribué</span><b>{i.quantity_assigned}</b></div><div className={available<=0?'stock-out':available<=i.stock_minimum?'stock-low':''}><span>Disponible</span><b>{available}</b></div></div><div className="inventory-mobile-location">📍 {i.location||'Non défini'}</div>{manager&&<div className="inventory-mobile-actions"><button className="secondary small" onClick={e=>{e.stopPropagation();void move(i,'STOCK_IN')}}>+ Stock</button><button className="ghost small" onClick={e=>{e.stopPropagation();void move(i,'STOCK_OUT')}}>- Stock</button><button className="ghost small" onClick={e=>{e.stopPropagation();void reserve(i)}}>Réserver</button></div>}</article>})}</div></div>
 {manager&&<aside className="panel"><h2><Boxes size={18}/> {selected?'Modifier':'Nouvelle référence'}</h2><form className="form-grid" onSubmit={save} key={selected?.id||'new'}><label>Catégorie<input name="category" defaultValue={selected?.category||''} required/></label><label>Constructeur<input name="manufacturer" defaultValue={selected?.manufacturer||''}/></label><label className="full">Modèle<input name="model" defaultValue={selected?.model||''} required/></label><label>Référence<input name="reference" defaultValue={selected?.reference||''}/></label><label>Prix unitaire €<input name="unit_price" type="number" min="0" step="0.01" defaultValue={selected?.unit_price||0}/></label><label>Quantité totale<input name="quantity_total" type="number" min="0" defaultValue={selected?.quantity_total||0}/></label><label>Stock minimum<input name="stock_minimum" type="number" min="0" defaultValue={selected?.stock_minimum||0}/></label><label>Emplacement<input name="location" defaultValue={selected?.location||''}/></label><label className="full">Description<textarea name="description" defaultValue={selected?.description||''}/></label><label className="full"><span><input name="tracked" type="checkbox" defaultChecked={selected?.tracked_individually}/> Suivi unitaire / numéro de série</span></label><button className="primary full">Enregistrer</button></form></aside>}
 </div></div>
}
