import { FormEvent,useEffect,useMemo,useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { MessageSquarePlus,Plus,RotateCcw,Save,CheckCircle2 } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../auth/AuthProvider'
import type { Customer,Profile,Ticket } from '../lib/types'

const emptyTicket=():Partial<Ticket>=>({subject:'',requester:'',description:'',category:'',intervention_type:'',status:'',priority:'',assigned_to:null,arrival_at:new Date().toISOString(),planned_start:null,planned_end:null,is_blocking:false,parent_incident:null,general_incident_label:null,customer_id:null,customer_contact_id:null})
export function TicketsPage(){
 const {profile}=useAuth();const manager=profile?.role==='manager';const qc=useQueryClient();const [selected,setSelected]=useState<Partial<Ticket>|null>(null);const [search,setSearch]=useState('')
 const {data:tickets=[]}=useQuery({queryKey:['tickets'],queryFn:async()=>{const {data,error}=await supabase.from('tickets').select('*').order('arrival_at',{ascending:false});if(error)throw error;return data as Ticket[]}})
 const {data:profiles=[]}=useQuery({queryKey:['profiles'],queryFn:async()=>{const {data,error}=await supabase.from('profiles').select('*').eq('active',true).order('display_name');if(error)throw error;return data as Profile[]}})
 const {data:config=[]}=useQuery({queryKey:['config'],queryFn:async()=>{const {data,error}=await supabase.from('config_values').select('*').eq('active',true).order('sort_order');if(error)throw error;return data||[]}})
 const {data:customers=[]}=useQuery({queryKey:['customers'],queryFn:async()=>{const {data,error}=await supabase.from('customers').select('*').eq('active',true).order('name');if(error)throw error;return data as Customer[]}})
 const {data:comments=[]}=useQuery({queryKey:['comments',selected?.id],enabled:!!selected?.id,queryFn:async()=>{const {data,error}=await supabase.from('ticket_comments').select('*').eq('ticket_id',selected!.id!).order('created_at');if(error)throw error;return data||[]}})
 const cfg=(kind:string)=>config.filter((x:any)=>x.kind===kind)
 const defaultLabel=(kind:string,code:string)=>cfg(kind).find((x:any)=>x.code===code)?.label||''
 const rows=useMemo(()=>tickets.filter(t=>(t.ticket_number+' '+t.subject+' '+(t.requester||'')).toLowerCase().includes(search.toLowerCase())),[tickets,search])
 useEffect(()=>{if(selected&&!selected.id){setSelected(s=>({...s,status:s?.status||defaultLabel('status','new'),priority:s?.priority||defaultLabel('priority','normal'),category:s?.category||cfg('category')[0]?.label||'',intervention_type:s?.intervention_type||cfg('type')[0]?.label||''}))}},[config])
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const fd=new FormData(e.currentTarget);const row:any={subject:String(fd.get('subject')),requester:String(fd.get('requester')||'')||null,description:String(fd.get('description')||'')||null,category:String(fd.get('category')),intervention_type:String(fd.get('type')),status:String(fd.get('status')),priority:String(fd.get('priority')),assigned_to:manager?(String(fd.get('assigned_to')||'')||null):(profile?.id||null),customer_id:String(fd.get('customer_id')||'')||null,is_blocking:fd.get('blocking')==='on',parent_incident:String(fd.get('parent_incident')||'')||null,planned_start:fd.get('planned_start')?new Date(String(fd.get('planned_start'))).toISOString():null,planned_end:fd.get('planned_end')?new Date(String(fd.get('planned_end'))).toISOString():null}
  if(selected.id){const {error}=await supabase.from('tickets').update(row).eq('id',selected.id);if(error){alert(error.message);return}}else{row.ticket_number='INC-'+Date.now().toString().slice(-9);row.created_by=profile?.id;const {error}=await supabase.from('tickets').insert(row);if(error){alert(error.message);return}}
  setSelected(null);await qc.invalidateQueries({queryKey:['tickets']})
 }
 const addComment=async()=>{if(!selected?.id||!profile)return;const body=prompt('Commentaire');if(!body?.trim())return;const {error}=await supabase.from('ticket_comments').insert({ticket_id:selected.id,author_id:profile.id,body:body.trim()});if(error)alert(error.message);else await qc.invalidateQueries({queryKey:['comments',selected.id]})}
 const close=async()=>{if(!selected?.id)return;const resolution=prompt('Commentaire de résolution obligatoire');if(!resolution?.trim())return;const {error}=await supabase.rpc('close_ticket',{p_ticket_id:selected.id,p_resolution:resolution.trim()});if(error)alert(error.message);else{setSelected(null);await qc.invalidateQueries({queryKey:['tickets']})}}
 const reopen=async()=>{if(!selected?.id)return;const {error}=await supabase.rpc('reopen_ticket',{p_ticket_id:selected.id});if(error)alert(error.message);else{setSelected(null);await qc.invalidateQueries({queryKey:['tickets']})}}
 return <div className="page tickets-page"><header className="page-head"><div><h1>Tickets</h1><p>{manager?'Vue équipe complète':'Tes tickets et création de nouveaux tickets.'}</p></div><button className="primary page-primary-action" onClick={()=>setSelected({...emptyTicket(),assigned_to:manager?null:profile?.id||null})}><Plus size={16}/> Nouveau ticket</button></header>
 <div className="split"><div><section className="card module-filter-card"><div className="module-filter-title"><b>Recherche & filtres</b><span>{rows.length} résultat{rows.length>1?'s':''}</span></div><div className="module-filter-grid"><label className="wide-filter">Recherche<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Numéro, titre, utilisateur…"/></label></div></section><div className="table-wrap desktop-only"><table><thead><tr><th>Ticket</th><th>Client</th><th>Statut</th><th>Priorité</th><th>Technicien</th><th>Planifié</th></tr></thead><tbody>{rows.map(t=><tr key={t.id} onClick={()=>setSelected(t)} style={{cursor:'pointer'}}><td><b>{t.ticket_number}</b><br/><small>{t.subject}</small></td><td>{customers.find(c=>c.id===t.customer_id)?.name||'—'}</td><td><span className="badge">{t.status}</span></td><td>{t.priority}</td><td>{profiles.find(p=>p.id===t.assigned_to)?.display_name||'Non affecté'}</td><td>{t.planned_start?new Date(t.planned_start).toLocaleString('fr-FR'):'—'}</td></tr>)}</tbody></table></div>
 <div className="module-mobile-list">{rows.map(t=><article className="module-mobile-card" key={t.id} onClick={()=>setSelected(t)}><div className="module-mobile-head"><div><b>{t.ticket_number} • {t.subject}</b><small>{customers.find(c=>c.id===t.customer_id)?.name||t.requester||'Sans client'}</small></div><span className="badge">{t.status}</span></div><div className="module-mobile-meta"><div><span>Priorité</span><b>{t.priority}</b></div><div><span>Technicien</span><b>{profiles.find(p=>p.id===t.assigned_to)?.display_name||'Non affecté'}</b></div><div><span>Planifié</span><b>{t.planned_start?new Date(t.planned_start).toLocaleString('fr-FR'):'—'}</b></div><div><span>Bloquant</span><b>{t.is_blocking?'Oui':'Non'}</b></div></div></article>)}</div></div>
 {selected&&<aside className="panel detail-panel"><h2>{selected.id?selected.ticket_number:'Nouveau ticket'}</h2><form className="form-grid" onSubmit={save} key={selected.id||'new-ticket'}><label className="full">Titre<input name="subject" defaultValue={selected.subject||''} required/></label><label>Demandeur<input name="requester" defaultValue={selected.requester||''}/></label><label>Client<select name="customer_id" defaultValue={selected.customer_id||''}><option value="">— Aucun —</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Catégorie<select name="category" defaultValue={selected.category||''}>{cfg('category').map((x:any)=><option key={x.id}>{x.label}</option>)}</select></label><label>Type<select name="type" defaultValue={selected.intervention_type||''}>{cfg('type').map((x:any)=><option key={x.id}>{x.label}</option>)}</select></label><label>Statut<select name="status" defaultValue={selected.status||''}>{cfg('status').map((x:any)=><option key={x.id}>{x.label}</option>)}</select></label><label>Priorité<select name="priority" defaultValue={selected.priority||''}>{cfg('priority').map((x:any)=><option key={x.id}>{x.label}</option>)}</select></label><label>Technicien<select name="assigned_to" defaultValue={selected.assigned_to||''} disabled={!manager}><option value="">Non affecté</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label>Incident parent<input name="parent_incident" defaultValue={selected.parent_incident||''}/></label><label>Début planifié<input name="planned_start" type="datetime-local" defaultValue={selected.planned_start?selected.planned_start.slice(0,16):''}/></label><label>Fin planifiée<input name="planned_end" type="datetime-local" defaultValue={selected.planned_end?selected.planned_end.slice(0,16):''}/></label><label className="full"><span><input name="blocking" type="checkbox" defaultChecked={selected.is_blocking}/> Incident bloquant</span></label><label className="full">Description<textarea name="description" defaultValue={selected.description||''}/></label><button className="primary full"><Save size={15}/> Enregistrer</button></form>
 {selected.id&&<><div className="actions" style={{marginTop:10}}><button className="secondary" onClick={()=>void addComment()}><MessageSquarePlus size={15}/> Commenter</button><button className="primary" onClick={()=>void close()}><CheckCircle2 size={15}/> Clôturer</button>{selected.closed_at&&<button className="ghost" onClick={()=>void reopen()}><RotateCcw size={15}/> Rouvrir</button>}</div><h3>Commentaires</h3>{comments.map((c:any)=><div className="card" key={c.id}><b>{c.author_name||'Utilisateur'}</b><small> • {new Date(c.created_at).toLocaleString('fr-FR')}</small><p>{c.body}</p></div>)}</>}
 </aside>}</div></div>
}
