import { FormEvent,useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { KeyRound,Mail,Power,Trash2,UserPlus } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Profile,Role } from '../lib/types'

export function UsersPage(){
 const qc=useQueryClient();const [msg,setMsg]=useState('')
 const {data:users=[]}=useQuery({queryKey:['profiles'],queryFn:async()=>{const {data,error}=await supabase.from('profiles').select('*').order('display_name');if(error)throw error;return data as Profile[]}})
 const refresh=()=>qc.invalidateQueries({queryKey:['profiles']})
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setMsg('');const fd=new FormData(e.currentTarget);const body={display_name:String(fd.get('name')||''),email:String(fd.get('email')||''),password:String(fd.get('password')||''),role:String(fd.get('role')||'technician'),force_password_change:true};const {data,error}=await supabase.functions.invoke('manager-create-user',{body});if(error||data?.error){setMsg(data?.error||error?.message||'Erreur');return}e.currentTarget.reset();setMsg('Compte créé. Le mot de passe temporaire devra être changé.');await refresh()}
 const update=async(id:string,patch:Partial<Profile>)=>{const {error}=await supabase.from('profiles').update(patch).eq('id',id);if(error)alert(error.message);else await refresh()}
 const admin=async(operation:string,user_id:string,extra:Record<string,unknown>={})=>{const {data,error}=await supabase.functions.invoke('manager-user-admin',{body:{operation,user_id,...extra}});if(error||data?.error){alert(data?.error||error?.message);return false}await refresh();return true}
 const tempPassword=async(u:Profile)=>{const p=prompt('Nouveau mot de passe temporaire (10 caractères minimum)');if(!p)return;if(p.length<10){alert('10 caractères minimum');return}await admin('set_password',u.id,{password:p,force_change:true})}
 const changeEmail=async(u:Profile)=>{const email=prompt('Nouvel email',u.email||'');if(!email||email===u.email)return;await admin('update_email',u.id,{email})}
 const hardDelete=async(u:Profile)=>{const phrase='SUPPRIMER '+u.display_name.toUpperCase();if(prompt('Suppression définitive. Tape exactement : '+phrase)!==phrase)return;await admin('delete_user',u.id)}
 return <div className="page users-page"><header className="page-head"><div><h1>Utilisateurs & accès</h1><p>Managers et techniciens. Désactivation recommandée avant suppression définitive.</p></div></header>
 <section className="card"><h3 className="section-title">Créer un compte</h3><form className="form-grid" onSubmit={create}><label>Nom<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Mot de passe temporaire<input name="password" type="password" minLength={10} required/></label><label>Rôle<select name="role"><option value="technician">Technicien</option><option value="manager">Manager</option></select></label><div className="full actions"><button className="primary"><UserPlus size={16}/> Créer</button>{msg&&<span className="alert">{msg}</span>}</div></form></section>
 <div className="table-wrap desktop-only"><table><thead><tr><th>Utilisateur</th><th>Rôle</th><th>Statut</th><th>Créé</th><th>Dernière connexion</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.display_name}</b><br/><small>{u.email}</small></td><td><select value={u.role} onChange={e=>void update(u.id,{role:e.target.value as Role})}><option value="technician">Technicien</option><option value="manager">Manager</option></select></td><td><span className={'badge '+(u.active?'green':'red')}>{u.active?'Actif':'Désactivé'}</span>{u.force_password_change&&<><br/><small>Changement MDP requis</small></>}</td><td>{new Date(u.created_at).toLocaleDateString('fr-FR')}</td><td>{u.last_login_at?new Date(u.last_login_at).toLocaleString('fr-FR'):'—'}</td><td><div className="actions"><button className="ghost small" onClick={()=>void changeEmail(u)}><Mail size={14}/> Email</button><button className="ghost small" onClick={()=>void admin('send_reset',u.id)}><KeyRound size={14}/> Envoyer reset</button><button className="secondary small" onClick={()=>void tempPassword(u)}><KeyRound size={14}/> MDP temporaire</button><button className="ghost small" onClick={()=>void update(u.id,{active:!u.active})}><Power size={14}/> {u.active?'Désactiver':'Activer'}</button><button className="danger small" onClick={()=>void hardDelete(u)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>
 <div className="module-mobile-list">{users.map(u=><article className="module-mobile-card" key={u.id}><div className="module-mobile-head"><div><b>{u.display_name}</b><small>{u.email}</small></div><span className={'badge '+(u.active?'green':'red')}>{u.active?'Actif':'Désactivé'}</span></div><div className="module-mobile-meta"><div><span>Rôle</span><b>{u.role==='manager'?'Manager':'Technicien'}</b></div><div><span>Créé</span><b>{new Date(u.created_at).toLocaleDateString('fr-FR')}</b></div><div><span>Dernière connexion</span><b>{u.last_login_at?new Date(u.last_login_at).toLocaleString('fr-FR'):'—'}</b></div><div><span>Mot de passe</span><b>{u.force_password_change?'Changement requis':'OK'}</b></div></div><label>Rôle<select value={u.role} onChange={e=>void update(u.id,{role:e.target.value as Role})}><option value="technician">Technicien</option><option value="manager">Manager</option></select></label><div className="module-mobile-actions"><button className="ghost small" onClick={()=>void changeEmail(u)}><Mail size={14}/> Email</button><button className="ghost small" onClick={()=>void admin('send_reset',u.id)}><KeyRound size={14}/> Reset</button><button className="secondary small" onClick={()=>void tempPassword(u)}><KeyRound size={14}/> MDP temp.</button><button className="ghost small" onClick={()=>void update(u.id,{active:!u.active})}><Power size={14}/> {u.active?'Désactiver':'Activer'}</button><button className="danger small" onClick={()=>void hardDelete(u)}><Trash2 size={14}/> Supprimer</button></div></article>)}</div>
 </div>
}
